version: '3'
services:
  redis-server:
    image: 'redis'
    restart: always
  my-socket-app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - redis-server
    command: nodemon socket.js