version: '3'
services:
  my-socket-app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    restart: always
    networks: 
      - mynet      
    command: nodemon socket.js
networks:
  mynet: 
    external: true  